# Generated by Django 4.1.7 on 2023-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_details',
            field=models.TextField(verbose_name='Makale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Makale Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Makale Adı'),
        ),
    ]
