# Generated by Django 4.1.7 on 2023-02-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_article_article_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
    ]
